# Generated by Django 2.2.5 on 2019-09-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='surname',
        ),
    ]
