# Generated by Django 2.2.5 on 2019-09-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_app', '0002_auto_20190921_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
