# Generated by Django 2.2.5 on 2019-09-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_app', '0003_doctors_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='heal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=128)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary_app.animals')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary_app.doctors')),
                ('services', models.ManyToManyField(to='veterinary_app.services')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary_app.status')),
            ],
        ),
    ]
