# Generated by Django 2.2.5 on 2019-09-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_app', '0004_animals_heal_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heal',
            old_name='owner',
            new_name='owner_name',
        ),
        migrations.AddField(
            model_name='heal',
            name='owner_surname',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
